ClassTools.Patterns.Multiton: Removed multiton classes. Now only using metaclasses. This is because the classes only provided a slight ease of use improvement. Also, when the user wanted to use 2 different metaclasses in 2 different base classes, they could not:
```
TypeError: Error when calling the metaclass bases
  metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```